
-- " Plug 'airblade/vim-gitgutter'
-- " Plug 'tpope/vim-surround' " this is the select an object and surround it with brackets or change its surrounding brackets
-- " Plug 'nvim-lua/plenary.nvim' " required for telescope
-- " Plug 'nvim-telescope/telescope.nvim' " a fuzzy search plugin for neovim (fzf replacement)
-- " Plug 'EdenEast/nightfox.nvim' " color scheme
-- " Plug 'preservim/nerdtree' " tree folder manager
-- " Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
-- " Plug 'glepnir/indent-guides.nvim' "indentation 
-- Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
-- Plug 'junegunn/fzf.vim'
-- call plug#end()
